[project]
name = "analytics-operator-consumption-forecasting-ml"
version = "0.0.1"
requires-python = "==3.10.20"
dependencies = [
  "torch==2.11.0",
  "ray[client,train]==2.55.0",
  "tqdm==4.67.3", # better progress bars
  "operator-lib @ git+https://github.com/SENERGY-Platform/analytics-operator-lib-python.git@v1.3.6",
  "darts==0.44.1",
  "pytorch-lightning==2.5.2",
  "prophet>=1.1.1"
]

[global]
extra-index-url = "https://download.pytorch.org/whl/cpu"

[tool.uv]
package = false